import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("C:\\Users\\AJAY\\OneDrive\\Dokumen\\Desktop\\note2.csv")
print(df)
plt.bar(df['period'],df['Region'])
plt.xlabel('X-axis label')
plt.ylabel('Y-axis label')
plt.title('Bar Plot')
plt.show()
plt.stem(df['Count'],df['Region'])
plt.xlabel('X-axis label')
plt.ylabel('Y-axis label')
plt.title('stem plot')
plt.show()
plt.stackplot(df['Count'],df['Region'])
plt.xlabel('X-axis label')
plt.ylabel('Y-axis label')
plt.title('stackplot Plot')
plt.show()
plt.scatter(df['period'],df['Count'])
plt.xlabel('X-axis label')
plt.ylabel('Y-axis label')
plt.title('scatter Plot')
plt.show()